// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HillaryHairCare.Migrations
{
    [DbContext(typeof(HillaryHairCareDbContext))]
    [Migration("20241204200527_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillaryHairCare.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentTime = new DateTime(2021, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Status = "Scheduled",
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentTime = new DateTime(2021, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Status = "Scheduled",
                            StylistId = 2
                        },
                        new
                        {
                            Id = 3,
                            AppointmentTime = new DateTime(2021, 1, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Status = "Scheduled",
                            StylistId = 3
                        },
                        new
                        {
                            Id = 4,
                            AppointmentTime = new DateTime(2021, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 4,
                            Status = "Scheduled",
                            StylistId = 4
                        },
                        new
                        {
                            Id = 5,
                            AppointmentTime = new DateTime(2021, 1, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            Status = "Scheduled",
                            StylistId = 5
                        });
                });

            modelBuilder.Entity("HillaryHairCare.Models.AppointmentService", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            AppointmentId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            AppointmentId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            AppointmentId = 4,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("HillaryHairCare.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "example@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "example@gmail.com",
                            Name = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            Email = "smith@example.com",
                            Name = "John Smith"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jane@example.com",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 5,
                            Email = "hojodojo@hotmail.com",
                            Name = "John Johnson"
                        });
                });

            modelBuilder.Entity("HillaryHairCare.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A simple haircut",
                            Name = "Haircut",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Getting hair dyed",
                            Name = "Color",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Get your facial hair trimmed",
                            Name = "Beard trim",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A haircut, style, color, and highlights",
                            Name = "Eyebrow Waxing",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A perm",
                            Name = "Perm",
                            Price = 50.00m
                        });
                });

            modelBuilder.Entity("HillaryHairCare.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Is_Active = true,
                            Name = "Hillary",
                            Specialization = "Hair Stylist"
                        },
                        new
                        {
                            Id = 2,
                            Is_Active = true,
                            Name = "John",
                            Specialization = "Hair Stylist"
                        },
                        new
                        {
                            Id = 3,
                            Is_Active = true,
                            Name = "Jane",
                            Specialization = "Hair Stylist"
                        },
                        new
                        {
                            Id = 4,
                            Is_Active = true,
                            Name = "Smith",
                            Specialization = "Hair Stylist"
                        },
                        new
                        {
                            Id = 5,
                            Is_Active = true,
                            Name = "Johnson",
                            Specialization = "Hair Stylist"
                        });
                });

            modelBuilder.Entity("HillaryHairCare.Models.Appointment", b =>
                {
                    b.HasOne("HillaryHairCare.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillaryHairCare.Models.Stylist", "Stylist")
                        .WithMany()
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HillaryHairCare.Models.AppointmentService", b =>
                {
                    b.HasOne("HillaryHairCare.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillaryHairCare.Models.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HillaryHairCare.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("HillaryHairCare.Models.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });
#pragma warning restore 612, 618
        }
    }
}
